### PR TITLE
Greetings to my Strong Friends

### PR DESCRIPTION
**Pull request by GeryaM**
Hello Ladies, please check my code

### CODE REVIEW

**Comment by AlimAlan** [comment]
great job,Masha

**Review by AlimAlan — APPROVED** [review]
Approving

**Comment by az-16** [comment]
Great Masha, can you change your code pls? I want to see difference

**Review by AlimAlan — APPROVED** [review]
second approving

**Review by az-16 — APPROVED** [review]

**Review by GeryaM — COMMENTED** [review]
Please approve it

**Pull request merged**
