### PR TITLE
Replit

### PR DESCRIPTION
**Pull request by az-16**
Please review the code

### CODE REVIEW

**Review by GeryaM — COMMENTED** [review]
I like your approach

**Comment by AlimAlan** [comment]
Good Job Aizat!

**Review by jbahar — COMMENTED** [review]
it is great good job

**Review by jbahar — APPROVED** [review]
i Approve your code

**Review by GeryaM — APPROVED** [review]
I approved

**Review by AlimAlan — APPROVED** [review]
Approving your code

**Pull request merged**
