### PR TITLE
Meerim

### PR DESCRIPTION
**Pull request by AlimAlan**
i commited my code. July 1,2021

### CODE REVIEW

**Review by jbahar — COMMENTED** [review]
u did great but still u can use just with 1 loop and with the same loop with 2 if conditions you can find the Min and Max

**Review by GeryaM — CHANGES_REQUESTED** [review]
Hey Meerim, can you please change the approach

**Review by jbahar — CHANGES_REQUESTED** [review]
Meerim can you please use one loop and change ur code to shorter code?

**Comment by az-16** [comment]
Meerim good job

**Review by GeryaM — APPROVED** [review]
Well done, shorter👍🏻

**Review by az-16 — APPROVED** [review]
aproved keep going

**Review by jbahar — APPROVED** [review]
Good job

**Pull request merged**
